<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PassPlusChildPass</name>
   <tag></tag>
   <elementGuidId>2a1e7e4b-8fdf-47a8-9b12-54abb05991cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span/div[1]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span/div[1]/div/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
